name: JS Actions

on: [push]

jobs:
  action:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      
      - name: hello-action
        uses: ./.github/actions/hello-world
        with:
          first-greeting: "Learning GitHub Actions using JS : 1"
          second-greeting: "Learning GitHub Actions using JS : 2"
          third-greeting: "Learning GitHub Actions using JS: 3"
